import Head from "next/head";
import Image from "next/image";
import {
  Inter,
  Pacifico,
  Bungee,
  Monoton,
  Megrim,
  Orbitron,
  Sacramento,
} from "next/font/google";
import React, { useState } from "react";
import Dot3D from "@/components/DotLines";

const inter = Inter({ subsets: ["latin"] });
const pacifico = Pacifico({ subsets: ["latin"], weight: ["400"] });
const bungee = Bungee({ subsets: ["latin"], weight: ["400"] });
const monoton = Monoton({ subsets: ["latin"], weight: ["400"] });
const megrim = Megrim({ subsets: ["latin"], weight: ["400"] });
const orbitron = Orbitron({ subsets: ["latin"], weight: ["400"] });
const sacramento = Sacramento({ subsets: ["latin"], weight: ["400"] });

export default function Home() {
  const [isRunning, setIsRunning] = useState(false);
  const [startProximity, setStartProximity] = useState(null);
  const [startRead, setStartRead] = useState(null);
  const handleClick = () => {
    console.log("olar");
    setIsRunning(!isRunning);

    // Get the DOM elements
    const heroElement = document.querySelector(".bg-hero");
    const h1Element = document.querySelector(".screen-text");

    // Add a class to the hero element to start the animation
    heroElement && heroElement.classList.toggle("bg-black");

    // Remove the "glow" class from the h1 element
    h1Element && h1Element.classList.toggle("flickering");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative bg-primary">
        <div className="bg-hero bg-cover bg-no-repeat bg-center snap-y">
          <div className="absolute h-screen w-screen">
            <Dot3D isRunning={isRunning} />
          </div>
          <section
            onClick={handleClick}
            className="container relative w-full h-screen mx-auto p-[4rem] z-1 flex justify-center"
          >
            <h1 className={`${bungee.className} glow screen-text`}>
              Click to start
            </h1>
          </section>
        </div>
      </div>
    </>
  );
}
